language: python
sudo: false
cache: false
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
env:
  - DJANGO=1.11
  - DJANGO=2.0
os:
  - linux
matrix:
  include:
    - { python: 2.7, env: TOXENV=flake8 }
    - { python: 2.7, env: TOXENV=flakeplus }
    - { python: 2.7, env: TOXENV=pydocstyle }
    - { python: 3.5, env: TOXENV=apicheck }
    - { python: 3.5, env: TOXENV=linkcheck }
    - { python: 3.5, env: TOXENV=cov }
  exclude:
    - { python: 2.7, env: DJANGO=2.0 }
    - { python: pypy, env: DJANGO=2.0 }
install: travis_retry pip install -U tox-travis
services: rabbitmq
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
