language: python
dist: bionic
cache: false
before_install:
  - sudo apt update
  - sudo apt install -y wget
  - wget http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
  - sudo apt-key add erlang_solutions.asc
  - sudo apt install -y sqlite
  - sudo apt install -y erlang
  - sudo apt install -y erlang-nox
  - sudo apt install -y rabbitmq-server
  - sudo /etc/init.d/rabbitmq-server start
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
os:
  - linux
matrix:
  include:
    - { python: 3.6, env: TOXENV=upgradebeat130 }
    - { python: 3.6, env: TOXENV=upgradebeat140 }
    - { python: 3.8, env: TOXENV=flake8 }
    - { python: 3.8, env: TOXENV=pydocstyle }
install: travis_retry pip install -U tox-travis
services: rabbitmq
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
